/** Stable machine-readable error codes returned in `error.code`. */
export const ERROR_CODES = {
  // 400
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  // 401
  AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  // 403
  FORBIDDEN: 'FORBIDDEN',
  CSRF_REJECTED: 'CSRF_REJECTED',
  SELF_APPROVAL_FORBIDDEN: 'SELF_APPROVAL_FORBIDDEN',
  SEGREGATION_OF_DUTIES: 'SEGREGATION_OF_DUTIES',
  NOT_ASSIGNED_ROLE: 'NOT_ASSIGNED_ROLE',
  WING_NOT_ASSIGNED: 'WING_NOT_ASSIGNED',
  CLAIMED_BY_OTHER: 'CLAIMED_BY_OTHER',
  FIELD_NOT_EDITABLE: 'FIELD_NOT_EDITABLE',
  PASSWORD_CHANGE_REQUIRED: 'PASSWORD_CHANGE_REQUIRED',
  // 404
  NOT_FOUND: 'NOT_FOUND',
  // 409
  CONFLICT: 'CONFLICT',
  VERSION_CONFLICT: 'VERSION_CONFLICT',
  DUPLICATE_KEY: 'DUPLICATE_KEY',
  // 413 / 415
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  UNSUPPORTED_FILE_TYPE: 'UNSUPPORTED_FILE_TYPE',
  // 422
  BUSINESS_RULE_VIOLATION: 'BUSINESS_RULE_VIOLATION',
  INVALID_TRANSITION: 'INVALID_TRANSITION',
  TRANSACTION_NOT_EDITABLE: 'TRANSACTION_NOT_EDITABLE',
  DUPLICATE_UNRESOLVED: 'DUPLICATE_UNRESOLVED',
  DUPLICATE_CONFIRMED: 'DUPLICATE_CONFIRMED',
  NO_ROUTING_RULE: 'NO_ROUTING_RULE',
  DEFAULT_RULE_REQUIRED: 'DEFAULT_RULE_REQUIRED',
  // 429
  RATE_LIMITED: 'RATE_LIMITED',
  // 500
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
